name: "打包推送 Docker 镜像"
description: "打包 Docker 镜像并推送到 Docker Hub"
inputs:
  login_repository:
    description: "docker/login-action 的 registry 参数"
    default: "docker.io"
    required: true
  login_username:
    description: "docker/login-action 的 username 参数"
    required: true
  login_password:
    description: "docker/login-action 的 password 参数"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
      with:
        filter: blob:none
        show-progress: false
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.login_repository }}
        username: ${{ inputs.login_username }}
        password: ${{ inputs.login_password }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache