name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@main
    - name: 安装 pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: false
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: lts/*
        cache: ''