on:
  push:
jobs:
  another-job:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-pnpm-install@main
      - run: |
          node --version
          pnpm --version