name: 持续集成

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  setup-node-environment-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - name: Check Node and PNPM versions
        run: |
          set -x
          which pnpm
