on:
  push:
env:
  TZ: Asia/Shanghai
jobs:
  another-job:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-pnpm-install@main
      - name: Check Node and PNPM versions
        run: |
          set -x
          node --version
          pnpm --version
          date
          pwd