name: 持续集成

on:
  push:

env:
  TZ: Asia/Shanghai

jobs:
  setup-node-environment-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - name: Check Node and PNPM versions
        run: |
          set -x
          which pnpm

  docker-build-push-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: yanhao98/semantic-release-action@main
        id: semantic
      - name: Print the new release version
        run: |
          echo ${{ steps.semantic.outputs.next_release_published }}
          echo ${{ steps.semantic.outputs.next_release_version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: yanhao98/composite-actions/docker-build-push@main
        id: docker-build-push
        with:
          build_file: ./docker-build-push/Dockerfile
          build_platforms: linux/amd64
          build_push: ${{ github.ref_type == 'tag' }}
          build_load: true
          metadata_images: |
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/docker-example
            ghcr.io/${{ github.repository }}
          metadata_tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Check Docker image
        run: |
          set -x;
          docker images;
          docker run --rm ${{ steps.docker-build-push.outputs.imageid }} whoami;
