on:
  push:
env:
  TZ: Asia/Shanghai
jobs:
  another-job:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-pnpm-install@a4fd8410307a8e42fee3e072f746b04718b29556
      - name: Check Node and PNPM versions
        run: |
          set -x
          node --version
          pnpm --version
          date
          pwd
          ls -al