name: 持续集成

on:
  push:

env:
  TZ: Asia/Shanghai

jobs:
  setup-node-environment-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - name: Check Node and PNPM versions
        run: |
          set -x
          which pnpm
  docker-build-push-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/docker-build-push@main
        with:
          login_username: ${{ secrets.DOCKERHUB_USERNAME }}
          login_password: ${{ secrets.DOCKERHUB_TOKEN }}
          build_file: ./docker-build-push/Dockerfile
          build_platforms: linux/amd64
          build_push: false
          build_load: true
          build_tags: image-test
      - name: Check Docker image
        run: |
          set -x
          docker images